export interface Product {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;
  images: string[];
  ingredients: string[];
  usage: string;
  benefits: string[];
  category: "weight-loss" | "supplement" | "detox";
  featured?: boolean;
}

export const products: Product[] = [
  {
    id: "1",
    slug: "tra-giam-can-collagen",
    name: "Trà Giảm Cân Collagen Thái Lan",
    description: "Trà giảm cân kết hợp collagen giúp da đẹp, dáng thon.",
    price: 250000,
    images: ["/images/products/san-pham-1.jpg"],
    ingredients: [
      "Trà xanh hữu cơ",
      "Collagen thủy phân",
      "Chiết xuất thảo mộc",
    ],
    usage: "Uống 1 gói mỗi tối trước khi đi ngủ 30 phút.",
    benefits: ["Giảm cân hiệu quả", "Dưỡng da sáng mịn", "Cải thiện giấc ngủ"],
    category: "weight-loss",
    featured: true,
  },
  {
    id: "2",
    slug: "vien-uong-giam-can-premium",
    name: "Viên Uống Giảm Cân Premium",
    description: "Viên uống giảm cân cao cấp từ thảo dược thiên nhiên",
    price: 350000,
    images: ["/images/products/san-pham-2.jpg"],
    ingredients: ["Chiết xuất trà xanh", "L-Carnitine", "Garcinia Cambogia"],
    usage: "Uống 2 viên mỗi ngày trước bữa ăn sáng",
    benefits: [
      "Đốt cháy mỡ thừa",
      "Tăng cường trao đổi chất",
      "Kiểm soát cảm giác thèm ăn",
    ],
    category: "weight-loss",
    featured: true,
  },
  {
    id: "3",
    slug: "bot-protein-giam-can",
    name: "Bột Protein Giảm Cân",
    description: "Bột protein thực vật hỗ trợ giảm cân hiệu quả",
    price: 450000,
    images: ["/images/products/san-pham-3.jpg"],
    ingredients: [
      "Protein đậu nành",
      "Protein đậu Hà Lan",
      "Hương vani tự nhiên",
    ],
    usage: "Pha 2 muỗng với 300ml nước, uống thay thế bữa sáng",
    benefits: ["Giảm cân lành mạnh", "Duy trì cơ bắp", "Tăng cường năng lượng"],
    category: "supplement",
  },
  {
    id: "4",
    slug: "tra-detox-thao-moc",
    name: "Trà Detox Thảo Mộc",
    description: "Trà detox từ các loại thảo mộc tự nhiên",
    price: 200000,
    images: ["/images/products/san-pham-4.jpg"],
    ingredients: ["Hoa cúc", "Atiso", "Khổ qua", "Cỏ ngọt"],
    usage: "Uống 1 gói mỗi sáng sau khi thức dậy",
    benefits: ["Thải độc cơ thể", "Thanh lọc gan", "Làm đẹp da"],
    category: "detox",
  },
  {
    id: "5",
    slug: "vien-giam-can-night-time",
    name: "Viên Giảm Cân Night Time",
    description: "Viên uống giảm cân đặc biệt cho buổi tối",
    price: 280000,
    images: ["/images/products/san-pham-5.jpg"],
    ingredients: ["Chiết xuất trà hoa cúc", "Magnolia", "L-Theanine"],
    usage: "Uống 1 viên trước khi đi ngủ 30 phút",
    benefits: [
      "Giảm cân khi ngủ",
      "Cải thiện chất lượng giấc ngủ",
      "Giảm stress",
    ],
    category: "weight-loss",
  },
  {
    id: "6",
    slug: "smoothie-giam-can",
    name: "Bột Smoothie Giảm Cân",
    description: "Bột smoothie organic giàu dinh dưỡng",
    price: 320000,
    images: ["/images/products/san-pham-6.jpg"],
    ingredients: ["Bột rau củ hữu cơ", "Hạt chia", "Protein thực vật"],
    usage: "Pha với 250ml sữa hạnh nhân hoặc nước",
    benefits: [
      "Bổ sung dinh dưỡng",
      "Giảm cân tự nhiên",
      "Tăng cường sức khỏe",
    ],
    category: "supplement",
  },
  {
    id: "7",
    slug: "cafe-giam-can",
    name: "Cà Phê Giảm Cân",
    description: "Cà phê giảm cân hương vị đậm đà",
    price: 220000,
    images: ["/images/products/san-pham-7.jpg"],
    ingredients: ["Cà phê Arabica", "L-Carnitine", "Chiết xuất trà xanh"],
    usage: "Pha 1 gói với 200ml nước nóng, uống buổi sáng",
    benefits: ["Tăng cường đốt mỡ", "Tỉnh táo", "Kiểm soát cân nặng"],
    category: "weight-loss",
  },
  {
    id: "8",
    slug: "combo-detox-7-ngay",
    name: "Combo Detox 7 Ngày",
    description: "Bộ sản phẩm detox toàn diện trong 7 ngày",
    price: 550000,
    images: ["/images/products/san-pham-8.jpg"],
    ingredients: ["Trà detox sáng", "Nước ép rau củ", "Trà detox tối"],
    usage: "Theo lịch trình 7 ngày được cung cấp",
    benefits: ["Giảm 2-3kg", "Thanh lọc cơ thể", "Da sáng mịn"],
    category: "detox",
    featured: true,
  },
  {
    id: "9",
    slug: "vien-giam-can-thai-doc",
    name: "Viên Giảm Cân Thải Độc",
    description: "Viên uống kết hợp giảm cân và thải độc",
    price: 380000,
    images: ["/images/products/san-pham-9.jpg"],
    ingredients: ["Spirulina", "Chlorella", "Tảo xoắn"],
    usage: "Uống 2 viên/ngày trước bữa ăn trưa",
    benefits: ["Thải độc gan", "Giảm mỡ bụng", "Tăng đề kháng"],
    category: "supplement",
  },
  {
    id: "10",
    slug: "tra-giam-can-hoa-qua",
    name: "Trà Giảm Cân Hoa Quả",
    description: "Trà giảm cân vị hoa quả tự nhiên",
    price: 180000,
    images: ["/images/products/san-pham-10.jpg"],
    ingredients: ["Táo", "Dâu tây", "Việt quất", "Trà xanh"],
    usage: "Uống 2 lần/ngày sau bữa ăn",
    benefits: ["Giảm cân tự nhiên", "Bổ sung vitamin", "Tăng cường miễn dịch"],
    category: "weight-loss",
  },
  {
    id: "11",
    slug: "vien-giam-can-metabolic",
    name: "Viên Giảm Cân Metabolic",
    description: "Viên uống tăng cường trao đổi chất",
    price: 420000,
    images: ["/images/products/san-pham-11.jpg"],
    ingredients: ["Green Tea Extract", "Caffeine", "Chromium Picolinate"],
    usage: "Uống 1 viên trước mỗi bữa ăn chính",
    benefits: [
      "Tăng tốc độ trao đổi chất",
      "Đốt cháy mỡ",
      "Kiểm soát đường huyết",
    ],
    category: "weight-loss",
  },
  {
    id: "12",
    slug: "bot-protein-vegan",
    name: "Bột Protein Thuần Chay",
    description: "Bột protein thực vật cho người ăn chay",
    price: 480000,
    images: ["/images/products/san-pham-12.jpg"],
    ingredients: ["Protein đậu Hà Lan", "Protein gạo", "Protein hạt bí"],
    usage: "Pha 2 muỗng với sữa thực vật",
    benefits: [
      "Giảm cân cho người ăn chay",
      "Duy trì cơ bắp",
      "Cung cấp năng lượng",
    ],
    category: "supplement",
  },
  {
    id: "13",
    slug: "tra-detox-mat-gan",
    name: "Trà Detox Mật Gan",
    description: "Trà detox chuyên biệt cho gan",
    price: 230000,
    images: ["/images/products/san-pham-13.jpg"],
    ingredients: ["Atiso", "Cà gai leo", "Diệp hạ châu"],
    usage: "Uống 2 lần/ngày sau bữa ăn",
    benefits: ["Giải độc gan", "Hỗ trợ tiêu hóa", "Làm đẹp da"],
    category: "detox",
  },
  {
    id: "14",
    slug: "vien-giam-can-premium-plus",
    name: "Viên Giảm Cân Premium Plus",
    description: "Viên uống giảm cân cao cấp phiên bản nâng cấp",
    price: 520000,
    images: ["/images/products/san-pham-14.jpg"],
    ingredients: ["CLA", "Green Coffee Bean Extract", "Raspberry Ketones"],
    usage: "Uống 2 viên/ngày, sáng và chiều",
    benefits: ["Giảm cân nhanh", "Săn chắc cơ thể", "Tăng năng lượng"],
    category: "weight-loss",
    featured: true,
  },
  {
    id: "15",
    slug: "smoothie-rau-cu",
    name: "Bột Smoothie Rau Củ",
    description: "Bột smoothie từ rau củ organic",
    price: 280000,
    images: ["/images/products/san-pham-15.jpg"],
    ingredients: ["Cải xoăn", "Cần tây", "Củ dền", "Cà rốt"],
    usage: "Pha với 300ml nước lọc hoặc nước dừa",
    benefits: ["Detox tự nhiên", "Giảm cân", "Tăng cường vitamin"],
    category: "detox",
  },
  {
    id: "16",
    slug: "vien-uong-dot-mo",
    name: "Viên Uống Đốt Mỡ",
    description: "Viên uống hỗ trợ đốt mỡ mạnh mẽ",
    price: 390000,
    images: ["/images/products/san-pham-16.jpg"],
    ingredients: [
      "L-Carnitine",
      "Caffeine Anhydrous",
      "Cayenne Pepper Extract",
    ],
    usage: "Uống 1 viên trước khi tập thể dục",
    benefits: ["Đốt mỡ nhanh", "Tăng năng lượng", "Hỗ trợ tập luyện"],
    category: "weight-loss",
  },
  {
    id: "17",
    slug: "tra-giam-can-dong-y",
    name: "Trà Giảm Cân Đông Y",
    description: "Trà giảm cân theo phương pháp Đông y",
    price: 290000,
    images: ["/images/products/san-pham-17.jpg"],
    ingredients: ["Hà thủ ô", "Quy giáp", "Cam thảo", "Hoài sơn"],
    usage: "Uống 1 gói mỗi tối trước khi đi ngủ",
    benefits: ["Giảm cân an toàn", "Cải thiện giấc ngủ", "Bổ sung dưỡng chất"],
    category: "weight-loss",
  },
  {
    id: "18",
    slug: "combo-giam-can-30-ngay",
    name: "Combo Giảm Cân 30 Ngày",
    description: "Bộ sản phẩm giảm cân toàn diện trong 30 ngày",
    price: 1200000,
    images: ["/images/products/san-pham-18.jpg"],
    ingredients: ["Viên giảm cân", "Trà detox", "Bột protein"],
    usage: "Theo lịch trình 30 ngày được cung cấp",
    benefits: ["Giảm 5-8kg", "Thay đổi thói quen", "Kết quả lâu dài"],
    category: "weight-loss",
    featured: true,
  },
  {
    id: "19",
    slug: "bot-giam-can-dau-do",
    name: "Bột Giảm Cân Đậu Đỏ",
    description: "Bột dinh dưỡng từ đậu đỏ giúp giảm cân",
    price: 260000,
    images: ["/images/products/san-pham-19.jpg"],
    ingredients: ["Đậu đỏ", "Yến mạch", "Hạt chia"],
    usage: "Pha 3 muỗng với 250ml sữa đậu nành",
    benefits: ["Giảm cân", "No lâu", "Giàu protein"],
    category: "supplement",
  },
  {
    id: "20",
    slug: "vien-giam-can-dot-mo-dem",
    name: "Viên Giảm Cân Đốt Mỡ Đêm",
    description: "Viên uống đốt mỡ chuyên biệt cho ban đêm",
    price: 340000,
    images: ["/images/products/san-pham-20.jpg"],
    ingredients: ["Green Tea Extract", "L-Carnitine", "Passion Flower Extract"],
    usage: "Uống 1 viên trước khi đi ngủ",
    benefits: ["Đốt mỡ khi ngủ", "Ngủ ngon", "Không kích thích"],
    category: "weight-loss",
  },
  {
    id: "21",
    slug: "tra-detox-hoa-qua",
    name: "Trà Detox Hoa Quả",
    description: "Trà detox từ hoa quả tự nhiên",
    price: 190000,
    images: ["/images/products/san-pham-21.jpg"],
    ingredients: ["Táo", "Lê", "Cam", "Chanh"],
    usage: "Uống 2 lần/ngày sau bữa ăn",
    benefits: ["Thải độc", "Giảm cân", "Đẹp da"],
    category: "detox",
  },
  {
    id: "22",
    slug: "vien-giam-can-thao-duoc",
    name: "Viên Giảm Cân Thảo Dược",
    description: "Viên uống giảm cân từ thảo dược tự nhiên",
    price: 310000,
    images: ["/images/products/san-pham-22.jpg"],
    ingredients: ["Trà xanh", "Nhân sâm", "Đông trùng hạ thảo"],
    usage: "Uống 2 viên/ngày trước bữa ăn",
    benefits: ["Giảm cân tự nhiên", "Tăng đề kháng", "Bổ sung năng lượng"],
    category: "weight-loss",
  },
  {
    id: "23",
    slug: "bot-protein-premium",
    name: "Bột Protein Premium",
    description: "Bột protein cao cấp hỗ trợ giảm cân",
    price: 550000,
    images: ["/images/products/san-pham-23.jpg"],
    ingredients: ["Whey Protein Isolate", "Casein", "BCAA"],
    usage: "Pha 2 muỗng với 300ml nước",
    benefits: ["Giảm mỡ", "Tăng cơ", "Phục hồi nhanh"],
    category: "supplement",
    featured: true,
  },
  {
    id: "24",
    slug: "tra-detox-premium",
    name: "Trà Detox Premium",
    description: "Trà detox cao cấp từ các loại thảo mộc",
    price: 280000,
    images: ["/images/products/san-pham-24.jpg"],
    ingredients: ["Hoa hồng", "Atiso", "Bạc hà", "Cam thảo"],
    usage: "Uống 1 gói mỗi sáng và tối",
    benefits: ["Thải độc toàn diện", "Giảm cân", "Làm đẹp da"],
    category: "detox",
  },
  {
    id: "25",
    slug: "vien-giam-can-super-slim",
    name: "Viên Giảm Cân Super Slim",
    description: "Viên uống giảm cân siêu hiệu quả",
    price: 460000,
    images: ["/images/products/san-pham-25.jpg"],
    ingredients: ["Garcinia Cambogia", "Green Coffee Bean", "African Mango"],
    usage: "Uống 2 viên/ngày trước bữa ăn sáng và trưa",
    benefits: ["Giảm cân nhanh", "Kiểm soát cơn đói", "Đốt mỡ hiệu quả"],
    category: "weight-loss",
    featured: true,
  },
];

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find((product) => product.slug === slug);
};

export const getFeaturedProducts = (): Product[] => {
  return products.filter((product) => product.featured);
};
